## Using NumPy

In [8]:
import numpy as np

ls = [1,2,3,4,5]
# converting to ndarray
arr = np.array(ls)
print(arr)

arr1 = np.random.random(3)
print(arr1)



[1 2 3 4 5]
[0.50380985 0.41079256 0.72763983]


In [6]:
arr = np.random.randint(1,6,10)
print(arr)

[2 2 5 4 5 2 4 4 3 3]


## NUmpy assignments


In [28]:
import numpy as np
a = np.arange(5)
print(a)

## number of elements in the array == product of the shape of array i.e rows*col for 2D arrays | 3D rows*cols*no of arrays
# 2d Arrays
a1 = np.arange(1,21).reshape(4,5)
print(a1)

# 3d arrays
a2 = np.arange(1,21).reshape(1,4,5)
print(a2)

## Attributes

print('*'*40)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

print('*'*40)
print(a1.ndim)
print(a1.shape)
print(a1.size)
print(a1.dtype)

print('*'*40)
print(a2.ndim)
print(a2.shape)
print(a2.size)
print(a2.dtype)



[0 1 2 3 4]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]]
****************************************
1
(5,)
5
int64
****************************************
2
(4, 5)
20
int64
****************************************
3
(1, 4, 5)
20
int64


In [35]:
# using empty() -- has garbage values , only allocates memeory
a = np.empty((3,5))
print(a)
print(a.shape)

## create array and fill with specified values
print('*'*40)
a1 = np.full((3,5),10)
print(a1)

# creates and assigns float value 0.
print('*'*40)
a2 = np.zeros((3,5))
print(a2)

# creates and assigns float value 1.
print('*'*40)
a2 = np.ones((3,5))
print(a2)



[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
(3, 5)
****************************************
[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]
****************************************
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
****************************************
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [36]:
# using arange to create array with value in a range
a = np.arange(14,54)
print(a)

[14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37
 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


In [39]:
# creating using arange and then using reshape to add dimensions
a = np.arange(1,41)
print(a)
print('*'*40)
a1 = a.reshape((4,10))
print(a1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]
****************************************
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]]


In [46]:
# operations on 2D array
a = np.arange(1,16).reshape(5,3)
print(a)

print('*'*40)
print(a+4)

print('*'*40)
print(a*2)

print('*'*40)
print(a-3)

print('*'*40)
print(a/2)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
****************************************
[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
****************************************
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]
 [26 28 30]]
****************************************
[[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
****************************************
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]
 [5.  5.5 6. ]
 [6.5 7.  7.5]]


In [64]:
# OPerations between two 2D Arrays
a = np.arange(1,10).reshape(3,3)
print(a)

a2 = np.arange(11,20).reshape(3,3)
print(a2)

print('*'*40)
print(a+a2)

print('*'*40)
print(a-a2)

print('*'*40)
print(a.dot(a2))

print('*'*40)
print(a/a2)

# using sum(),min(),max() on 2D array and axis=0/axis=1
print('*'*40)
print(a)
print('-'*40)
print(a.sum(axis=0))
print(a.max(axis=0))
print(a.min(axis=0))


# using transpose
print('*'*20)
a2.transpose()

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
****************************************
[[12 14 16]
 [18 20 22]
 [24 26 28]]
****************************************
[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]
****************************************
[[ 90  96 102]
 [216 231 246]
 [342 366 390]]
****************************************
[[0.09090909 0.16666667 0.23076923]
 [0.28571429 0.33333333 0.375     ]
 [0.41176471 0.44444444 0.47368421]]
****************************************
[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------------------------------------
[12 15 18]
[7 8 9]
[1 2 3]
********************


array([[11, 14, 17],
       [12, 15, 18],
       [13, 16, 19]])