## Using NumPy Assignments

In [1]:
import math
from cmath import sqrt

import numpy as np

## Indexing Qs
a = np.arange(1,31).reshape(5,6)
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]


In [5]:

print(a[:3,:4])

[[ 1  2  3  4]
 [ 7  8  9 10]
 [13 14 15 16]]


In [9]:
print(a[:3,4:5])


[[ 5]
 [11]
 [17]]


In [10]:
print(a[2:4,:])

[[13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [11]:
print(a[:,2:5])

[[ 3  4  5]
 [ 9 10 11]
 [15 16 17]
 [21 22 23]
 [27 28 29]]


In [14]:
##Return odd values from matrix -- method 1
a1 = np.where(a%2 != 0)
print(a[a1])

# Return only even values from matrix -- method 2
print(a[a%2 ==0])

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]


In [23]:
# replace all even values with -1 in a matrix

print(a)
print('*'*40)
res = np.where(a%2==0,-1,a)
print(res)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
****************************************
****************************************
[[ 1 -1  3 -1  5 -1]
 [ 7 -1  9 -1 11 -1]
 [13 -1 15 -1 17 -1]
 [19 -1 21 -1 23 -1]
 [25 -1 27 -1 29 -1]]


In [29]:
# appending one array to another
a = np.random.randint(1,11,10)
print(a)

a2 = np.arange(1,9)
print(a2)

np.append(a,a2)

[10  4  9  9  1  5  4  5  8  7]
[1 2 3 4 5 6 7 8]


array([10,  4,  9,  9,  1,  5,  4,  5,  8,  7,  1,  2,  3,  4,  5,  6,  7,
        8])

In [31]:
## make 1 d array of 16 elements into 2d array with 2 rows
a1 = np.arange(1,17)
print(a1)

a1.reshape(2,8)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [36]:
## sorting array with random values in ascending and descending order
a3 = np.random.randint(13,40,12)
#print(np.sort(a3))
print(np.sort(a3)[::-1])

[39 35 35 30 27 25 19 18 17 17 16 14]


In [44]:
## from an array of random integers extract prime numbers
import math
a3 = np.random.randint(1,17,16)
print(a3)

## practice isPrime logic
def isPrime(n):
    if n>1:
        for i in range(2,int(math.sqrt(n)+1)):
            if n%i ==0:
                 return False

        return True
    else:
        return False


l2 = list(filter(isPrime,a3))
print(l2)

[ 6 12 11  9 16  6 10  6  4  5 11  5 12 14  8  2]
[np.int32(11), np.int32(5), np.int32(11), np.int32(5), np.int32(2)]


In [1]:
 ## using numpy